! This an autogenerated file using simos.generator
! Please do not edit. 
! user defined code can be added at the marked locations.
! Babak Ommani, Oil and Gas Department, MARINTEK 

! a named entity with unit
! Generated with marmo:basic:NamedEntityWithUnit version [object Object]
!
!------------------------------------------------------------------------------
!******************************************************************************
module class_marmo_basic_NamedEntityWithUnit
    !---------------------------------------------------------------------------
    !use statements
    !using general modules
    !******************************************************************************
    !using general modules
    use class_string
    use iso_fortran_env, only: sp => real32, dp => real64
    use string_util
    use h5accessor_f
    use iso_c_binding, only: c_null_char, c_char
    use exceptions, only: throw, exception_occurred
    use class_io_exception, only: io_exception
    use class_illegal_state_exception, only: illegal_state_exception
    !******************************************************************************
    !using custom modules. Classes are aliased to avoid name clashing
#   include "exceptions.h"
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED USE START @@@@@
!@@@@@ USER DEFINED USE End   @@@@@
    !---------------------------------------------------------------------------
    implicit none
    private
    !---------------------------------------------------------------------------
    public :: NamedEntityWithUnit
    type   :: NamedEntityWithUnit
        private
        ! data unit.
        type(String), public :: unit
        ! variable name for named accessing
        type(String), public :: name
        ! instance description
        type(String), public :: description
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED PROPERTIES START @@@@@
!@@@@@ USER DEFINED PROPERTIES End   @@@@@
    !---------------------------------------------------------------------------
    contains
        private

        generic, public :: default_init => default_initFromSingle, default_initFromSingleWiNameFromChar, default_initFromSingleWiNameFromString
        generic, public :: save_HDF5 => save_HDF5_toNewDataBaseWiDefaultName, save_HDF5_toNewDataBase, save_HDF5_toExistingDataBase
        generic, public :: load_HDF5 => load_HDF5_fromDefaultFile, load_HDF5_fromFileNameAndEntityName, load_HDF5_fromGroupIndex
        procedure, public :: isValid
        procedure, public :: destroy

        ! Private procedures
        procedure :: default_initFromSingle
        procedure :: default_initFromSingleWiNameFromChar
        procedure :: default_initFromSingleWiNameFromString
        procedure :: save_HDF5_toNewDataBaseWiDefaultName
        procedure :: save_HDF5_toNewDataBase
        procedure :: save_HDF5_toExistingDataBase
        procedure :: load_HDF5_fromDefaultFile
        procedure :: load_HDF5_fromFileNameAndEntityName
        procedure :: load_HDF5_fromGroupIndex
        procedure :: destroy_unit
        procedure :: destroy_name
        procedure :: destroy_description
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED PROCEDURE DECLARATIONS START @@@@@
!@@@@@ USER DEFINED PROCEDURE DECLARATIONS End   @@@@@
    !---------------------------------------------------------------------------
    end type NamedEntityWithUnit
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED INTERFACE DECLARATIONS START @@@@@
!@@@@@ USER DEFINED INTERFACE DECLARATIONS End   @@@@@
    !---------------------------------------------------------------------------
contains
    !---------------------------------------------------------------------------
    !-------------------------------Destroyer-----------------------------------
    pure subroutine destroy(this)
        class(NamedEntityWithUnit), intent(inout) :: this
        call this%destroy_unit()
        call this%destroy_name()
        call this%destroy_description()
    end subroutine destroy
    !-------------------------------Destroyers----------------------------------
    !---------------------------------------------------------------------------
    pure subroutine destroy_unit(this)
        class(NamedEntityWithUnit), intent(inout) :: this
        call this%unit%destroy()
    end subroutine destroy_unit
    !---------------------------------------------------------------------------
    pure subroutine destroy_name(this)
        class(NamedEntityWithUnit), intent(inout) :: this
        call this%name%destroy()
    end subroutine destroy_name
    !---------------------------------------------------------------------------
    pure subroutine destroy_description(this)
        class(NamedEntityWithUnit), intent(inout) :: this
        call this%description%destroy()
    end subroutine destroy_description
    !-------------------------------Default initialization----------------------
    pure subroutine default_initFromSingleWiNameFromChar(this, insName)
        class(NamedEntityWithUnit), intent(inout) :: this
        character(*), intent(in) :: insName
        
        call this%default_initFromSingle()
        ! Set the default name of the object
        this%name = string(insName)
    end subroutine default_initFromSingleWiNameFromChar
    
    pure subroutine default_initFromSingleWiNameFromString(this, insName)
        class(NamedEntityWithUnit), intent(inout) :: this
        type(String), intent(in) :: insName
        
        call this%default_initFromSingle()
        ! Set the default name of the object
        this%name = insName
    end subroutine default_initFromSingleWiNameFromString
    
    pure subroutine default_initFromSingle(this)
        class(NamedEntityWithUnit), intent(inout) :: this
        
        ! Set the default name of the object
        this%name = string('NamedEntityWithUnit')
    end subroutine default_initFromSingle
    
    !-------------------------------Set and get---------------------------------

    !-----------------------------  Save  --------------------------------------
    subroutine save_HDF5_toNewDataBaseWiDefaultName(this)
        implicit none
        class(NamedEntityWithUnit) :: this
        call this%save_HDF5_toNewDataBase(this%name+'.h5')
    end subroutine save_HDF5_toNewDataBaseWiDefaultName
    
    !---------------------------------------------------------------------------
    
    subroutine save_HDF5_toNewDataBase(this,fileName)
        implicit none
        class(NamedEntityWithUnit) :: this
        type(String), intent(in) :: fileName
        ! Internal variables
        type(string) :: error_message
        logical :: there
        integer :: dataBaseID, groupID, errorj
        
        if (.not. this%isValid()) then
            error_message = 'Cannot save model that is not valid'
            call throw(illegal_state_exception(error_message))
            end if
        ! Initialization
        errorj=0
        call h5a_initialize('no config required')
        
        ! Destroy database if already present
        inquire(file=fileName%toChars(),exist=there)
        if (there) then
            errorj = H5A_RemoveDatabase( fileName%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
                error_message = 'Failed to remove existing file at ' // fileName%toChars()
                call throw(io_exception(error_message))
                return
            end if
        end if
        
        ! Create new database
        dataBaseID = H5A_OpenOrCreateDatabase(fileName%toChars() // c_null_char)
        if (H5A_IS_ERROR(dataBaseID)) then
            error_message = 'Failed to create file ' // fileName%toChars()
            call throw(io_exception(error_message))
            return
        end if
        
        ! Save the current object if it is valid
        if (this%isValid()) then
            ! Specify file format
            errorj = H5A_SetFormat(dataBaseID, 'simos_r0' // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
                error_message = 'Failed to set format of file'
                call throw(io_exception(error_message))
                return
            end if
            groupID = H5A_OpenOrCreateEntity(dataBaseID, this%name%toChars() // c_null_char)
            if (H5A_IS_ERROR(groupID)) then
                error_message = 'Failed to create entity ' //                           &
                        this%name%toChars() // ' in file ' // fileName%toChars()
                call throw(io_exception(error_message))
                return
            end if
            call this%save_HDF5_toExistingDataBase(groupID)
            errorj=H5A_CloseEntity(groupID)
        end if
        
        ! Close the data base
        errorj = H5A_CloseDatabase(dataBaseID)
        if (H5A_IS_ERROR(groupID)) then
            error_message = 'Failed to close file ' // fileName%toChars()
            call throw(io_exception(error_message))
            return
        end if
    end subroutine save_HDF5_toNewDataBase
    
    !---------------------------------------------------------------------------
    
    subroutine save_HDF5_toExistingDataBase(this,groupIndex)
        implicit none
        class(NamedEntityWithUnit) :: this
        integer, intent(in) :: groupIndex
        ! Internal variables
        integer :: errorj
        type(string) :: error_message
        type(string) :: str
        
        ! Some initializations
        errorj=0
        
        ! Save the class of the object
        errorj=h5a_setType(groupIndex,'marmo:basic:NamedEntityWithUnit' // c_null_char)
        if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of marmo:basic:NamedEntityWithUnit'
            call throw(io_exception(error_message))
            return
        end if
        
        !-------------------------------------------------------------------------
        ! Save property unit
        !-------------------------------------------------------------------------
        if (.not.(this%unit%isEmpty())) then
            errorj = H5A_writeStringWithLength(groupIndex, 'unit' // c_null_char,this%unit%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of unit'
            call throw(io_exception(error_message))
                return
            end if
        end if
        
        !-------------------------------------------------------------------------
        ! Save property name
        !-------------------------------------------------------------------------
        if (.not.(this%name%isEmpty())) then
            errorj = H5A_writeStringWithLength(groupIndex, 'name' // c_null_char,this%name%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of name'
            call throw(io_exception(error_message))
                return
            end if
        end if
        
        !-------------------------------------------------------------------------
        ! Save property description
        !-------------------------------------------------------------------------
        if (.not.(this%description%isEmpty())) then
            errorj = H5A_writeStringWithLength(groupIndex, 'description' // c_null_char,this%description%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of description'
            call throw(io_exception(error_message))
                return
            end if
        end if

        ! Set properties order
        errorj = h5a_setOrder(groupIndex,'unit,name,description' // c_null_char)
        if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of description'
            call throw(io_exception(error_message))
            return
        end if
    end subroutine save_HDF5_toExistingDataBase
    !-----------------------------  Load  --------------------------------------
    subroutine load_HDF5_fromDefaultFile(this)
        implicit none
        class(NamedEntityWithUnit) :: this
        !Internal variables, for proper cloning 
        type(String) :: fileName
        type(String) :: name
        
        name = this%name   !has to be cloned before loading
        fileName = name%toChars()+'.h5'
        call this%load_HDF5(fileName, name)
    end subroutine load_HDF5_fromDefaultFile
    
    !---------------------------------------------------------------------------
    
    subroutine load_HDF5_fromFileNameAndEntityName(this, fileName, entityName)
        implicit none
        class(NamedEntityWithUnit) :: this
        type(String), intent(in) :: fileName
        type(String), intent(in) :: entityName
        ! Internal variables
        logical :: there
        type(string) :: error_message
        integer :: dataBaseID, groupID, error
        integer :: i
        integer :: n
        character(kind=c_char), allocatable :: cchars(:)
        character(len=:), allocatable :: fileFormat
        
        ! Initialization
        call h5a_initialize('no config required')
        
        ! Open database file if present
        inquire(file=fileName%toChars(), exist=there)
        if (there) then
            call this%destroy()
            dataBaseID = H5A_OpenDatabaseReadOnly(fileName%toChars() // c_null_char)
            if (H5A_IS_ERROR(dataBaseID)) then
                error_message = 'Unable to open file ' // fileName%toChars() // ' for reading'
                call throw(io_exception(error_message))
                return
            end if
        else
            error_message = 'HDF5 file not found: ' // fileName%toChars()
            call throw(io_exception(error_message))
            return
        end if
        
        ! Check format attribute
        error = H5A_GetFormatSize(dataBaseID, n)
        if (.not. H5A_IS_ERROR(error)) then
            allocate(cchars(n))
            allocate(character(len=n) :: fileFormat)
            error = H5A_GetFormat(dataBaseID, cchars)
            if (.not. H5A_IS_ERROR(error)) then
                do i = 1, n
                    fileFormat(i:i) = cchars(i)
                    ! Replace any newline or null characters with whitespace so that they may be trimmed away (kind of hacky)
                    if (cchars(i) == new_line(cchars) .or. cchars(i) == c_null_char) then
                        fileFormat(i:i) = ' '
                    end if
                end do
                if (trim(fileFormat) /= 'simos_r0') then
                    error_message = "Cannot read file with format '" // fileFormat // "', " //       &
                                    "only 'simos_r0' is supported. Error during read of file " // fileName%toChars()
                    call throw(io_exception(error_message))
                    goto 8000
                end if
            end if
        end if
        if (H5A_IS_ERROR(error)) then
            error_message = 'Error determining format of file ' // fileName%toChars()
            call throw(io_exception(error_message))
            goto 8000
        end if
        
        ! Get the first groupIndex and load the object
        groupID = H5A_OpenEntity(dataBaseID, entityName%toChars() // c_null_char)
        if (.not. H5A_IS_ERROR(groupID)) then
            call this%load_HDF5(groupID)
            error=H5A_CloseEntity(groupID)
            if (exception_occurred()) goto 8000
        else
            error_message = 'Group not found: ' // entityName%toChars()
            call throw(io_exception(error_message))
            goto 8000
        end if
        
        ! Finally - close the database
        8000 continue
        error = H5A_CloseDatabase(dataBaseID)
        ! Silently ignore any error during close
    end subroutine load_HDF5_fromFileNameAndEntityName
    
    !---------------------------------------------------------------------------
    
    subroutine load_HDF5_fromGroupIndex(this, groupIndex)
        implicit none
        class(NamedEntityWithUnit) :: this
        integer, intent(in) :: groupIndex
        ! Internal variables
        type(string) :: error_message
        integer :: error
        integer :: sv
        integer :: strSize
        character(kind=c_char), allocatable :: cc_a(:)
        
        ! Some initializations
        error=0
        
        ! Check the class of the object (to be implemented later)
        !-------------------------------------------------------------------------
        ! Load property unit
        !-------------------------------------------------------------------------
        error= H5A_getStringLength(groupIndex, 'unit' // c_null_char,strSize)
        if (error.ge.0) then
            if (allocated(cc_a)) deallocate(cc_a)
            allocate(character :: cc_a(strSize+1),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NamedEntityWithUnit, error when trying &
                    &to allocate name for unit'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            error = H5A_ReadStringWithLength(groupIndex, 'unit' // c_null_char,cc_a)
            cc_a(strSize+1) = c_null_char
            this%unit=String(cc_a)
            this%unit=this%unit%trim()
            deallocate(cc_a)
            if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NamedEntityWithUnit'        &
                    + ' - failed to open property unit'
            call throw(io_exception(error_message))
                return
            end if
        end if
        !-------------------------------------------------------------------------
        ! Load property name
        !-------------------------------------------------------------------------
        error= H5A_getStringLength(groupIndex, 'name' // c_null_char,strSize)
        if (error.ge.0) then
            if (allocated(cc_a)) deallocate(cc_a)
            allocate(character :: cc_a(strSize+1),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NamedEntityWithUnit, error when trying &
                    &to allocate name for name'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            error = H5A_ReadStringWithLength(groupIndex, 'name' // c_null_char,cc_a)
            cc_a(strSize+1) = c_null_char
            this%name=String(cc_a)
            this%name=this%name%trim()
            deallocate(cc_a)
            if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NamedEntityWithUnit'        &
                    + ' - failed to open property name'
            call throw(io_exception(error_message))
                return
            end if
        end if
        !-------------------------------------------------------------------------
        ! Load property description
        !-------------------------------------------------------------------------
        error= H5A_getStringLength(groupIndex, 'description' // c_null_char,strSize)
        if (error.ge.0) then
            if (allocated(cc_a)) deallocate(cc_a)
            allocate(character :: cc_a(strSize+1),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NamedEntityWithUnit, error when trying &
                    &to allocate name for description'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            error = H5A_ReadStringWithLength(groupIndex, 'description' // c_null_char,cc_a)
            cc_a(strSize+1) = c_null_char
            this%description=String(cc_a)
            this%description=this%description%trim()
            deallocate(cc_a)
            if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NamedEntityWithUnit'        &
                    + ' - failed to open property description'
            call throw(io_exception(error_message))
                return
            end if
        end if
    end subroutine load_HDF5_fromGroupIndex
    !-------------------------------Is valid -----------------------------------
    logical elemental function isValid(this)
        class(NamedEntityWithUnit), intent(in) :: this
        isValid = .true.
        if (this%name%isEmpty()) isValid = .false.
    end function
    !-------------------------------Resize functions----------------------------

    !---------------------------------------------------------------------------
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED PROCEDURES START @@@@@
!@@@@@ USER DEFINED PROCEDURES End   @@@@@
!---------------------------------------------------------------------------
end module  class_marmo_basic_NamedEntityWithUnit
!******************************************************************************