! This an autogenerated file using simos.generator
! Please do not edit. 
! user defined code can be added at the marked locations.
! Babak Ommani, Oil and Gas Department, MARINTEK 

! a class for sea state
! Generated with freves:SeaState version [object Object]
!
!------------------------------------------------------------------------------
!******************************************************************************
module class_freves_SeaState
    !---------------------------------------------------------------------------
    !use statements
    !using general modules
    !******************************************************************************
    !using general modules
    use String
    !******************************************************************************
    !using custom modules
    use class_freves_Spectrum
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED USE START @@@@@
!@@@@@ USER DEFINED USE End   @@@@@
    !---------------------------------------------------------------------------
    implicit none
    private
    !---------------------------------------------------------------------------
    public :: freves_SeaState
    type   :: freves_SeaState
        private
            type(freves_Spectrum), dimension(:), allocatable, public :: waveSpectrums    !Specs.
            type(String), public :: name    !variable name for named accessing
            type(String), public :: description    !instance description
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED PROPERTIES START @@@@@
!@@@@@ USER DEFINED PROPERTIES End   @@@@@
    !---------------------------------------------------------------------------
    contains
        private
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED PROCEDURE DECLARATIONS START @@@@@
!@@@@@ USER DEFINED PROCEDURE DECLARATIONS End   @@@@@
    !---------------------------------------------------------------------------
    end type freves_SeaState
    !---------------------------------------------------------------------------
contains
    !---------------------------------------------------------------------------
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED PROCEDURES START @@@@@
!@@@@@ USER DEFINED PROCEDURES End   @@@@@
!---------------------------------------------------------------------------
end module  class_freves_SeaState
!******************************************************************************