! This an autogenerated file using simos.generator
! Please do not edit. 
! user defined code can be added at the marked locations.
! Babak Ommani, Oil and Gas Department, MARINTEK 

! data model for a non-equally spaced signal.
! Generated with marmo:containers:NonEquallySpacedSignal version [object Object]
!
!------------------------------------------------------------------------------
!******************************************************************************
module class_marmo_containers_NonEquallySpacedSignal
    !---------------------------------------------------------------------------
    !use statements
    !using general modules
    !******************************************************************************
    !using general modules
    use class_string
    use iso_fortran_env, only: sp => real32, dp => real64
    use string_util
    use h5accessor_f
    use iso_c_binding, only: c_null_char, c_char
    use exceptions, only: throw, exception_occurred
    use class_io_exception, only: io_exception
    use class_illegal_state_exception, only: illegal_state_exception
    !******************************************************************************
    !using custom modules. Classes are aliased to avoid name clashing
#   include "exceptions.h"
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED USE START @@@@@
!@@@@@ USER DEFINED USE End   @@@@@
    !---------------------------------------------------------------------------
    implicit none
    private
    !---------------------------------------------------------------------------
    public :: NonEquallySpacedSignal
    type   :: NonEquallySpacedSignal
        private
        ! name for the x value.
        type(String), public :: xname
        ! label for the x value.
        type(String), public :: xlabel
        ! description for the x value.
        type(String), public :: xdescription
        ! x signal unit
        type(String), public :: xunit
        ! x data points.
        real(dp), dimension(:), allocatable, public :: xvalue
        ! data points.
        real(dp), dimension(:), allocatable, public :: value
        ! signal unit
        type(String), public :: unit
        ! label for the y value.
        type(String), public :: label
        ! description of xy values to be used as legend.
        type(String), public :: legend
        ! variable name for named accessing
        type(String), public :: name
        ! instance description
        type(String), public :: description
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED PROPERTIES START @@@@@
!@@@@@ USER DEFINED PROPERTIES End   @@@@@
    !---------------------------------------------------------------------------
    contains
        private

        generic, public :: default_init => default_initFromSingle, default_initFromSingleWiNameFromChar, default_initFromSingleWiNameFromString
        generic, public :: save_HDF5 => save_HDF5_toNewDataBaseWiDefaultName, save_HDF5_toNewDataBase, save_HDF5_toExistingDataBase
        generic, public :: load_HDF5 => load_HDF5_fromDefaultFile, load_HDF5_fromFileNameAndEntityName, load_HDF5_fromGroupIndex
        procedure, public :: isValid
        procedure, public :: destroy
        !--- resize functions for single atomic arrays ----
        procedure, public :: resize_xvalue
        procedure, public :: resize_value
        ! Private procedures
        procedure :: default_initFromSingle
        procedure :: default_initFromSingleWiNameFromChar
        procedure :: default_initFromSingleWiNameFromString
        procedure :: save_HDF5_toNewDataBaseWiDefaultName
        procedure :: save_HDF5_toNewDataBase
        procedure :: save_HDF5_toExistingDataBase
        procedure :: load_HDF5_fromDefaultFile
        procedure :: load_HDF5_fromFileNameAndEntityName
        procedure :: load_HDF5_fromGroupIndex
        procedure :: destroy_xname
        procedure :: destroy_xlabel
        procedure :: destroy_xdescription
        procedure :: destroy_xunit
        procedure :: destroy_xvalue
        procedure :: destroy_value
        procedure :: destroy_unit
        procedure :: destroy_label
        procedure :: destroy_legend
        procedure :: destroy_name
        procedure :: destroy_description
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED PROCEDURE DECLARATIONS START @@@@@
!@@@@@ USER DEFINED PROCEDURE DECLARATIONS End   @@@@@
    !---------------------------------------------------------------------------
    end type NonEquallySpacedSignal
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED INTERFACE DECLARATIONS START @@@@@
!@@@@@ USER DEFINED INTERFACE DECLARATIONS End   @@@@@
    !---------------------------------------------------------------------------
contains
    !---------------------------------------------------------------------------
    !-------------------------------Destroyer-----------------------------------
    pure subroutine destroy(this)
        class(NonEquallySpacedSignal), intent(inout) :: this
        call this%destroy_xname()
        call this%destroy_xlabel()
        call this%destroy_xdescription()
        call this%destroy_xunit()
        call this%destroy_xvalue()
        call this%destroy_value()
        call this%destroy_unit()
        call this%destroy_label()
        call this%destroy_legend()
        call this%destroy_name()
        call this%destroy_description()
    end subroutine destroy
    !-------------------------------Destroyers----------------------------------
    !---------------------------------------------------------------------------
    pure subroutine destroy_xname(this)
        class(NonEquallySpacedSignal), intent(inout) :: this
        call this%xname%destroy()
    end subroutine destroy_xname
    !---------------------------------------------------------------------------
    pure subroutine destroy_xlabel(this)
        class(NonEquallySpacedSignal), intent(inout) :: this
        call this%xlabel%destroy()
    end subroutine destroy_xlabel
    !---------------------------------------------------------------------------
    pure subroutine destroy_xdescription(this)
        class(NonEquallySpacedSignal), intent(inout) :: this
        call this%xdescription%destroy()
    end subroutine destroy_xdescription
    !---------------------------------------------------------------------------
    pure subroutine destroy_xunit(this)
        class(NonEquallySpacedSignal), intent(inout) :: this
        call this%xunit%destroy()
    end subroutine destroy_xunit
    !---------------------------------------------------------------------------
    pure subroutine destroy_xvalue(this)
        class(NonEquallySpacedSignal), intent(inout) :: this
        if (allocated(this%xvalue)) deallocate(this%xvalue)
    end subroutine destroy_xvalue
    !---------------------------------------------------------------------------
    pure subroutine destroy_value(this)
        class(NonEquallySpacedSignal), intent(inout) :: this
        if (allocated(this%value)) deallocate(this%value)
    end subroutine destroy_value
    !---------------------------------------------------------------------------
    pure subroutine destroy_unit(this)
        class(NonEquallySpacedSignal), intent(inout) :: this
        call this%unit%destroy()
    end subroutine destroy_unit
    !---------------------------------------------------------------------------
    pure subroutine destroy_label(this)
        class(NonEquallySpacedSignal), intent(inout) :: this
        call this%label%destroy()
    end subroutine destroy_label
    !---------------------------------------------------------------------------
    pure subroutine destroy_legend(this)
        class(NonEquallySpacedSignal), intent(inout) :: this
        call this%legend%destroy()
    end subroutine destroy_legend
    !---------------------------------------------------------------------------
    pure subroutine destroy_name(this)
        class(NonEquallySpacedSignal), intent(inout) :: this
        call this%name%destroy()
    end subroutine destroy_name
    !---------------------------------------------------------------------------
    pure subroutine destroy_description(this)
        class(NonEquallySpacedSignal), intent(inout) :: this
        call this%description%destroy()
    end subroutine destroy_description
    !-------------------------------Default initialization----------------------
    pure subroutine default_initFromSingleWiNameFromChar(this, insName)
        class(NonEquallySpacedSignal), intent(inout) :: this
        character(*), intent(in) :: insName
        
        call this%default_initFromSingle()
        ! Set the default name of the object
        this%name = string(insName)
    end subroutine default_initFromSingleWiNameFromChar
    
    pure subroutine default_initFromSingleWiNameFromString(this, insName)
        class(NonEquallySpacedSignal), intent(inout) :: this
        type(String), intent(in) :: insName
        
        call this%default_initFromSingle()
        ! Set the default name of the object
        this%name = insName
    end subroutine default_initFromSingleWiNameFromString
    
    pure subroutine default_initFromSingle(this)
        class(NonEquallySpacedSignal), intent(inout) :: this
        
        ! Set the default name of the object
        this%name = string('NonEquallySpacedSignal')
    end subroutine default_initFromSingle
    
    !-------------------------------Set and get---------------------------------

    !-----------------------------  Save  --------------------------------------
    subroutine save_HDF5_toNewDataBaseWiDefaultName(this)
        implicit none
        class(NonEquallySpacedSignal) :: this
        call this%save_HDF5_toNewDataBase(this%name+'.h5')
    end subroutine save_HDF5_toNewDataBaseWiDefaultName
    
    !---------------------------------------------------------------------------
    
    subroutine save_HDF5_toNewDataBase(this,fileName)
        implicit none
        class(NonEquallySpacedSignal) :: this
        type(String), intent(in) :: fileName
        ! Internal variables
        type(string) :: error_message
        logical :: there
        integer :: dataBaseID, groupID, errorj
        
        if (.not. this%isValid()) then
            error_message = 'Cannot save model that is not valid'
            call throw(illegal_state_exception(error_message))
            end if
        ! Initialization
        errorj=0
        call h5a_initialize('no config required')
        
        ! Destroy database if already present
        inquire(file=fileName%toChars(),exist=there)
        if (there) then
            errorj = H5A_RemoveDatabase( fileName%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
                error_message = 'Failed to remove existing file at ' // fileName%toChars()
                call throw(io_exception(error_message))
                return
            end if
        end if
        
        ! Create new database
        dataBaseID = H5A_OpenOrCreateDatabase(fileName%toChars() // c_null_char)
        if (H5A_IS_ERROR(dataBaseID)) then
            error_message = 'Failed to create file ' // fileName%toChars()
            call throw(io_exception(error_message))
            return
        end if
        
        ! Save the current object if it is valid
        if (this%isValid()) then
            ! Specify file format
            errorj = H5A_SetFormat(dataBaseID, 'simos_r0' // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
                error_message = 'Failed to set format of file'
                call throw(io_exception(error_message))
                return
            end if
            groupID = H5A_OpenOrCreateEntity(dataBaseID, this%name%toChars() // c_null_char)
            if (H5A_IS_ERROR(groupID)) then
                error_message = 'Failed to create entity ' //                           &
                        this%name%toChars() // ' in file ' // fileName%toChars()
                call throw(io_exception(error_message))
                return
            end if
            call this%save_HDF5_toExistingDataBase(groupID)
            errorj=H5A_CloseEntity(groupID)
        end if
        
        ! Close the data base
        errorj = H5A_CloseDatabase(dataBaseID)
        if (H5A_IS_ERROR(groupID)) then
            error_message = 'Failed to close file ' // fileName%toChars()
            call throw(io_exception(error_message))
            return
        end if
    end subroutine save_HDF5_toNewDataBase
    
    !---------------------------------------------------------------------------
    
    subroutine save_HDF5_toExistingDataBase(this,groupIndex)
        implicit none
        class(NonEquallySpacedSignal) :: this
        integer, intent(in) :: groupIndex
        ! Internal variables
        integer :: errorj
        type(string) :: error_message
        type(string) :: str
        integer :: sv
        integer, dimension(:), allocatable :: diml
        
        ! Some initializations
        errorj=0
        
        ! Save the class of the object
        errorj=h5a_setType(groupIndex,'marmo:containers:NonEquallySpacedSignal' // c_null_char)
        if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of marmo:containers:NonEquallySpacedSignal'
            call throw(io_exception(error_message))
            return
        end if
        
        !-------------------------------------------------------------------------
        ! Save property xname
        !-------------------------------------------------------------------------
        if (.not.(this%xname%isEmpty())) then
            errorj = H5A_writeStringWithLength(groupIndex, 'xname' // c_null_char,this%xname%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of xname'
            call throw(io_exception(error_message))
                return
            end if
        end if
        
        !-------------------------------------------------------------------------
        ! Save property xlabel
        !-------------------------------------------------------------------------
        if (.not.(this%xlabel%isEmpty())) then
            errorj = H5A_writeStringWithLength(groupIndex, 'xlabel' // c_null_char,this%xlabel%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of xlabel'
            call throw(io_exception(error_message))
                return
            end if
        end if
        
        !-------------------------------------------------------------------------
        ! Save property xdescription
        !-------------------------------------------------------------------------
        if (.not.(this%xdescription%isEmpty())) then
            errorj = H5A_writeStringWithLength(groupIndex, 'xdescription' // c_null_char,this%xdescription%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of xdescription'
            call throw(io_exception(error_message))
                return
            end if
        end if
        
        !-------------------------------------------------------------------------
        ! Save property xunit
        !-------------------------------------------------------------------------
        if (.not.(this%xunit%isEmpty())) then
            errorj = H5A_writeStringWithLength(groupIndex, 'xunit' // c_null_char,this%xunit%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of xunit'
            call throw(io_exception(error_message))
                return
            end if
        end if
        
        !-------------------------------------------------------------------------
        ! Save property xvalue
        !-------------------------------------------------------------------------
        if (allocated(this%xvalue)) then
            if (allocated(diml)) deallocate(diml)
            allocate(diml(1),stat=sv)
            if (sv.ne.0) then
                errorj=-1
                error_message = 'Error during saving of NonEquallySpacedSignal, error when tryin&
                    &g to allocate diml array for xvalue'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            diml=shape(this%xvalue)
            errorj = H5A_WriteDoubleArray(groupIndex, 'xvalue' // c_null_char,1,diml,this%xvalue)
            if (H5A_IS_ERROR(errorj)) then
                error_message = 'Error during saving of xvalue'
                call throw(io_exception(error_message))
                return
            end if
            deallocate(diml)
        end if
        
        !-------------------------------------------------------------------------
        ! Save property value
        !-------------------------------------------------------------------------
        if (allocated(this%value)) then
            if (allocated(diml)) deallocate(diml)
            allocate(diml(1),stat=sv)
            if (sv.ne.0) then
                errorj=-1
                error_message = 'Error during saving of NonEquallySpacedSignal, error when tryin&
                    &g to allocate diml array for value'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            diml=shape(this%value)
            errorj = H5A_WriteDoubleArray(groupIndex, 'value' // c_null_char,1,diml,this%value)
            if (H5A_IS_ERROR(errorj)) then
                error_message = 'Error during saving of value'
                call throw(io_exception(error_message))
                return
            end if
            deallocate(diml)
        end if
        
        !-------------------------------------------------------------------------
        ! Save property unit
        !-------------------------------------------------------------------------
        if (.not.(this%unit%isEmpty())) then
            errorj = H5A_writeStringWithLength(groupIndex, 'unit' // c_null_char,this%unit%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of unit'
            call throw(io_exception(error_message))
                return
            end if
        end if
        
        !-------------------------------------------------------------------------
        ! Save property label
        !-------------------------------------------------------------------------
        if (.not.(this%label%isEmpty())) then
            errorj = H5A_writeStringWithLength(groupIndex, 'label' // c_null_char,this%label%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of label'
            call throw(io_exception(error_message))
                return
            end if
        end if
        
        !-------------------------------------------------------------------------
        ! Save property legend
        !-------------------------------------------------------------------------
        if (.not.(this%legend%isEmpty())) then
            errorj = H5A_writeStringWithLength(groupIndex, 'legend' // c_null_char,this%legend%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of legend'
            call throw(io_exception(error_message))
                return
            end if
        end if
        
        !-------------------------------------------------------------------------
        ! Save property name
        !-------------------------------------------------------------------------
        if (.not.(this%name%isEmpty())) then
            errorj = H5A_writeStringWithLength(groupIndex, 'name' // c_null_char,this%name%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of name'
            call throw(io_exception(error_message))
                return
            end if
        end if
        
        !-------------------------------------------------------------------------
        ! Save property description
        !-------------------------------------------------------------------------
        if (.not.(this%description%isEmpty())) then
            errorj = H5A_writeStringWithLength(groupIndex, 'description' // c_null_char,this%description%toChars() // c_null_char)
            if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of description'
            call throw(io_exception(error_message))
                return
            end if
        end if

        ! Set properties order
        errorj = h5a_setOrder(groupIndex,'xname,xlabel,xdescription,xunit,xvalue,value,u&
            &nit,label,legend,name,description' // c_null_char)
        if (H5A_IS_ERROR(errorj)) then
            error_message = 'Error during saving of description'
            call throw(io_exception(error_message))
            return
        end if
    end subroutine save_HDF5_toExistingDataBase
    !-----------------------------  Load  --------------------------------------
    subroutine load_HDF5_fromDefaultFile(this)
        implicit none
        class(NonEquallySpacedSignal) :: this
        !Internal variables, for proper cloning 
        type(String) :: fileName
        type(String) :: name
        
        name = this%name   !has to be cloned before loading
        fileName = name%toChars()+'.h5'
        call this%load_HDF5(fileName, name)
    end subroutine load_HDF5_fromDefaultFile
    
    !---------------------------------------------------------------------------
    
    subroutine load_HDF5_fromFileNameAndEntityName(this, fileName, entityName)
        implicit none
        class(NonEquallySpacedSignal) :: this
        type(String), intent(in) :: fileName
        type(String), intent(in) :: entityName
        ! Internal variables
        logical :: there
        type(string) :: error_message
        integer :: dataBaseID, groupID, error
        integer :: i
        integer :: n
        character(kind=c_char), allocatable :: cchars(:)
        character(len=:), allocatable :: fileFormat
        
        ! Initialization
        call h5a_initialize('no config required')
        
        ! Open database file if present
        inquire(file=fileName%toChars(), exist=there)
        if (there) then
            call this%destroy()
            dataBaseID = H5A_OpenDatabaseReadOnly(fileName%toChars() // c_null_char)
            if (H5A_IS_ERROR(dataBaseID)) then
                error_message = 'Unable to open file ' // fileName%toChars() // ' for reading'
                call throw(io_exception(error_message))
                return
            end if
        else
            error_message = 'HDF5 file not found: ' // fileName%toChars()
            call throw(io_exception(error_message))
            return
        end if
        
        ! Check format attribute
        error = H5A_GetFormatSize(dataBaseID, n)
        if (.not. H5A_IS_ERROR(error)) then
            allocate(cchars(n))
            allocate(character(len=n) :: fileFormat)
            error = H5A_GetFormat(dataBaseID, cchars)
            if (.not. H5A_IS_ERROR(error)) then
                do i = 1, n
                    fileFormat(i:i) = cchars(i)
                    ! Replace any newline or null characters with whitespace so that they may be trimmed away (kind of hacky)
                    if (cchars(i) == new_line(cchars) .or. cchars(i) == c_null_char) then
                        fileFormat(i:i) = ' '
                    end if
                end do
                if (trim(fileFormat) /= 'simos_r0') then
                    error_message = "Cannot read file with format '" // fileFormat // "', " //       &
                                    "only 'simos_r0' is supported. Error during read of file " // fileName%toChars()
                    call throw(io_exception(error_message))
                    goto 8000
                end if
            end if
        end if
        if (H5A_IS_ERROR(error)) then
            error_message = 'Error determining format of file ' // fileName%toChars()
            call throw(io_exception(error_message))
            goto 8000
        end if
        
        ! Get the first groupIndex and load the object
        groupID = H5A_OpenEntity(dataBaseID, entityName%toChars() // c_null_char)
        if (.not. H5A_IS_ERROR(groupID)) then
            call this%load_HDF5(groupID)
            error=H5A_CloseEntity(groupID)
            if (exception_occurred()) goto 8000
        else
            error_message = 'Group not found: ' // entityName%toChars()
            call throw(io_exception(error_message))
            goto 8000
        end if
        
        ! Finally - close the database
        8000 continue
        error = H5A_CloseDatabase(dataBaseID)
        ! Silently ignore any error during close
    end subroutine load_HDF5_fromFileNameAndEntityName
    
    !---------------------------------------------------------------------------
    
    subroutine load_HDF5_fromGroupIndex(this, groupIndex)
        implicit none
        class(NonEquallySpacedSignal) :: this
        integer, intent(in) :: groupIndex
        ! Internal variables
        type(string) :: error_message
        integer :: error
        integer :: sv
        real(dp), dimension(:), allocatable :: tmp_dp_matrix1
        integer, dimension(:), allocatable :: diml
        integer :: strSize
        character(kind=c_char), allocatable :: cc_a(:)
        
        ! Some initializations
        error=0
        
        ! Check the class of the object (to be implemented later)
        !-------------------------------------------------------------------------
        ! Load property xname
        !-------------------------------------------------------------------------
        error= H5A_getStringLength(groupIndex, 'xname' // c_null_char,strSize)
        if (error.ge.0) then
            if (allocated(cc_a)) deallocate(cc_a)
            allocate(character :: cc_a(strSize+1),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NonEquallySpacedSignal, error when tryi&
                    &ng to allocate name for xname'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            error = H5A_ReadStringWithLength(groupIndex, 'xname' // c_null_char,cc_a)
            cc_a(strSize+1) = c_null_char
            this%xname=String(cc_a)
            this%xname=this%xname%trim()
            deallocate(cc_a)
            if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NonEquallySpacedSignal'        &
                    + ' - failed to open property xname'
            call throw(io_exception(error_message))
                return
            end if
        end if
        !-------------------------------------------------------------------------
        ! Load property xlabel
        !-------------------------------------------------------------------------
        error= H5A_getStringLength(groupIndex, 'xlabel' // c_null_char,strSize)
        if (error.ge.0) then
            if (allocated(cc_a)) deallocate(cc_a)
            allocate(character :: cc_a(strSize+1),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NonEquallySpacedSignal, error when tryi&
                    &ng to allocate name for xlabel'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            error = H5A_ReadStringWithLength(groupIndex, 'xlabel' // c_null_char,cc_a)
            cc_a(strSize+1) = c_null_char
            this%xlabel=String(cc_a)
            this%xlabel=this%xlabel%trim()
            deallocate(cc_a)
            if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NonEquallySpacedSignal'        &
                    + ' - failed to open property xlabel'
            call throw(io_exception(error_message))
                return
            end if
        end if
        !-------------------------------------------------------------------------
        ! Load property xdescription
        !-------------------------------------------------------------------------
        error= H5A_getStringLength(groupIndex, 'xdescription' // c_null_char,strSize)
        if (error.ge.0) then
            if (allocated(cc_a)) deallocate(cc_a)
            allocate(character :: cc_a(strSize+1),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NonEquallySpacedSignal, error when tryi&
                    &ng to allocate name for xdescription'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            error = H5A_ReadStringWithLength(groupIndex, 'xdescription' // c_null_char,cc_a)
            cc_a(strSize+1) = c_null_char
            this%xdescription=String(cc_a)
            this%xdescription=this%xdescription%trim()
            deallocate(cc_a)
            if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NonEquallySpacedSignal'        &
                    + ' - failed to open property xdescription'
            call throw(io_exception(error_message))
                return
            end if
        end if
        !-------------------------------------------------------------------------
        ! Load property xunit
        !-------------------------------------------------------------------------
        error= H5A_getStringLength(groupIndex, 'xunit' // c_null_char,strSize)
        if (error.ge.0) then
            if (allocated(cc_a)) deallocate(cc_a)
            allocate(character :: cc_a(strSize+1),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NonEquallySpacedSignal, error when tryi&
                    &ng to allocate name for xunit'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            error = H5A_ReadStringWithLength(groupIndex, 'xunit' // c_null_char,cc_a)
            cc_a(strSize+1) = c_null_char
            this%xunit=String(cc_a)
            this%xunit=this%xunit%trim()
            deallocate(cc_a)
            if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NonEquallySpacedSignal'        &
                    + ' - failed to open property xunit'
            call throw(io_exception(error_message))
                return
            end if
        end if
        !-------------------------------------------------------------------------
        ! Load property xvalue
        !-------------------------------------------------------------------------
        if (allocated(diml)) deallocate(diml)
        allocate(diml(1),stat=sv)
        if (sv.ne.0) then
            error=-1
            error_message = 'Error during loading of NonEquallySpacedSignal, error when tryi&
                &ng to allocate diml array for xvalue'
            call throw(illegal_state_exception(error_message%toChars()))
            return
        end if
        error = H5A_GetArrayDims(groupIndex,'xvalue' // c_null_char, diml)
        if (error >= 0) then
            if (allocated(this%xvalue)) deallocate(this%xvalue)
            allocate(this%xvalue(diml(1)),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NonEquallySpacedSignal, error when tryi&
                    &ng to allocate array for xvalue'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
        error = H5A_ReadDoubleArray(groupIndex,'xvalue' // c_null_char, this%xvalue)
        if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NonEquallySpacedSignal' +        &
                    ' - failed to load property xvalue'
            call throw(io_exception(error_message))
            return
        end if
        end if
        deallocate(diml)
        !-------------------------------------------------------------------------
        ! Load property value
        !-------------------------------------------------------------------------
        if (allocated(diml)) deallocate(diml)
        allocate(diml(1),stat=sv)
        if (sv.ne.0) then
            error=-1
            error_message = 'Error during loading of NonEquallySpacedSignal, error when tryi&
                &ng to allocate diml array for value'
            call throw(illegal_state_exception(error_message%toChars()))
            return
        end if
        error = H5A_GetArrayDims(groupIndex,'value' // c_null_char, diml)
        if (error >= 0) then
            if (allocated(this%value)) deallocate(this%value)
            allocate(this%value(diml(1)),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NonEquallySpacedSignal, error when tryi&
                    &ng to allocate array for value'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
        error = H5A_ReadDoubleArray(groupIndex,'value' // c_null_char, this%value)
        if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NonEquallySpacedSignal' +        &
                    ' - failed to load property value'
            call throw(io_exception(error_message))
            return
        end if
        end if
        deallocate(diml)
        !-------------------------------------------------------------------------
        ! Load property unit
        !-------------------------------------------------------------------------
        error= H5A_getStringLength(groupIndex, 'unit' // c_null_char,strSize)
        if (error.ge.0) then
            if (allocated(cc_a)) deallocate(cc_a)
            allocate(character :: cc_a(strSize+1),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NonEquallySpacedSignal, error when tryi&
                    &ng to allocate name for unit'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            error = H5A_ReadStringWithLength(groupIndex, 'unit' // c_null_char,cc_a)
            cc_a(strSize+1) = c_null_char
            this%unit=String(cc_a)
            this%unit=this%unit%trim()
            deallocate(cc_a)
            if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NonEquallySpacedSignal'        &
                    + ' - failed to open property unit'
            call throw(io_exception(error_message))
                return
            end if
        end if
        !-------------------------------------------------------------------------
        ! Load property label
        !-------------------------------------------------------------------------
        error= H5A_getStringLength(groupIndex, 'label' // c_null_char,strSize)
        if (error.ge.0) then
            if (allocated(cc_a)) deallocate(cc_a)
            allocate(character :: cc_a(strSize+1),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NonEquallySpacedSignal, error when tryi&
                    &ng to allocate name for label'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            error = H5A_ReadStringWithLength(groupIndex, 'label' // c_null_char,cc_a)
            cc_a(strSize+1) = c_null_char
            this%label=String(cc_a)
            this%label=this%label%trim()
            deallocate(cc_a)
            if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NonEquallySpacedSignal'        &
                    + ' - failed to open property label'
            call throw(io_exception(error_message))
                return
            end if
        end if
        !-------------------------------------------------------------------------
        ! Load property legend
        !-------------------------------------------------------------------------
        error= H5A_getStringLength(groupIndex, 'legend' // c_null_char,strSize)
        if (error.ge.0) then
            if (allocated(cc_a)) deallocate(cc_a)
            allocate(character :: cc_a(strSize+1),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NonEquallySpacedSignal, error when tryi&
                    &ng to allocate name for legend'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            error = H5A_ReadStringWithLength(groupIndex, 'legend' // c_null_char,cc_a)
            cc_a(strSize+1) = c_null_char
            this%legend=String(cc_a)
            this%legend=this%legend%trim()
            deallocate(cc_a)
            if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NonEquallySpacedSignal'        &
                    + ' - failed to open property legend'
            call throw(io_exception(error_message))
                return
            end if
        end if
        !-------------------------------------------------------------------------
        ! Load property name
        !-------------------------------------------------------------------------
        error= H5A_getStringLength(groupIndex, 'name' // c_null_char,strSize)
        if (error.ge.0) then
            if (allocated(cc_a)) deallocate(cc_a)
            allocate(character :: cc_a(strSize+1),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NonEquallySpacedSignal, error when tryi&
                    &ng to allocate name for name'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            error = H5A_ReadStringWithLength(groupIndex, 'name' // c_null_char,cc_a)
            cc_a(strSize+1) = c_null_char
            this%name=String(cc_a)
            this%name=this%name%trim()
            deallocate(cc_a)
            if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NonEquallySpacedSignal'        &
                    + ' - failed to open property name'
            call throw(io_exception(error_message))
                return
            end if
        end if
        !-------------------------------------------------------------------------
        ! Load property description
        !-------------------------------------------------------------------------
        error= H5A_getStringLength(groupIndex, 'description' // c_null_char,strSize)
        if (error.ge.0) then
            if (allocated(cc_a)) deallocate(cc_a)
            allocate(character :: cc_a(strSize+1),stat=sv)
            if (sv.ne.0) then
                error=-1
                error_message = 'Error during loading of NonEquallySpacedSignal, error when tryi&
                    &ng to allocate name for description'
                call throw(illegal_state_exception(error_message%toChars()))
                return
            end if
            error = H5A_ReadStringWithLength(groupIndex, 'description' // c_null_char,cc_a)
            cc_a(strSize+1) = c_null_char
            this%description=String(cc_a)
            this%description=this%description%trim()
            deallocate(cc_a)
            if (H5A_IS_ERROR(error)) then
            error_message = 'Error during loading of NonEquallySpacedSignal'        &
                    + ' - failed to open property description'
            call throw(io_exception(error_message))
                return
            end if
        end if
    end subroutine load_HDF5_fromGroupIndex
    !-------------------------------Is valid -----------------------------------
    logical elemental function isValid(this)
        class(NonEquallySpacedSignal), intent(in) :: this
        isValid = .true.
        if (this%name%isEmpty()) isValid = .false.
    end function
    !-------------------------------Resize functions----------------------------
    !---------------------------------------------------------------------------
    subroutine resize_xvalue(this, n0)
        class(NonEquallySpacedSignal) :: this
        integer,intent(in) :: n0
        !internal variables
        integer :: error, sv
        type(string) :: error_message
        call this%destroy_xvalue()
        if (allocated(this%xvalue)) deallocate(this%xvalue)
        allocate(this%xvalue(n0),stat=sv)
        if (sv.ne.0) then
            error=-1
            error_message = 'Error during resizing in NonEquallySpacedSignal, error when try&
                &ing to allocate memory for xvalue'
            call throw(illegal_state_exception(error_message%toChars()))
            return
        end if
    end subroutine resize_xvalue
    !---------------------------------------------------------------------------
    subroutine resize_value(this, n0)
        class(NonEquallySpacedSignal) :: this
        integer,intent(in) :: n0
        !internal variables
        integer :: error, sv
        type(string) :: error_message
        call this%destroy_value()
        if (allocated(this%value)) deallocate(this%value)
        allocate(this%value(n0),stat=sv)
        if (sv.ne.0) then
            error=-1
            error_message = 'Error during resizing in NonEquallySpacedSignal, error when try&
                &ing to allocate memory for value'
            call throw(illegal_state_exception(error_message%toChars()))
            return
        end if
    end subroutine resize_value
    !---------------------------------------------------------------------------
    !---------------------------------------------------------------------------
!@@@@@ USER DEFINED PROCEDURES START @@@@@
!@@@@@ USER DEFINED PROCEDURES End   @@@@@
!---------------------------------------------------------------------------
end module  class_marmo_containers_NonEquallySpacedSignal
!******************************************************************************