#!/bin/bash
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Source configuration
source $SCRIPT_DIR/config.sh

echo "${PACKAGE_GENERATOR}.generatePackage('${PACKAGE_NAME}_${PACKAGE_VERSION}')" | $SHS_COMMAND
