//exports.simosPath = '.';


exports.langs = {'python': {'id': 'py', 
							'interp': 'lang/python'},
				 'python3': {'id': 'py3', 
							'interp': 'lang/python3'},	
				 'py3li': {'id': 'py3li', 
							'interp': 'lang/py3li'},
				 'python311': {'id': 'py311', 
							'interp': 'lang/python311'},													
				 'matlab': {'id': 'mat', 
    						'interp': 'lang/matlab'},
    			 'fortran': {'id': 'fort', 
    						'interp': 'lang/fortran'},
    			 'latdoc': {'id': 'ld', 
    						'interp': 'lang/latdoc'},
    			 'dmt'   : {'id': 'dmt', 
    						'interp': 'lang/dmt'},
    			 'dmt_migrator'   : {'id': 'dmig', 
							'interp': 'lang/dmt_migrator'},
				 'dmt_to_simos'   : {'id': 'ds', 
    						'interp': 'lang/dmt_to_simos'},
				 'typescript': {'id': 'ts',
							'interp': 'lang/ts'}}